/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WatchListsData struct for WatchListsData
type WatchListsData struct {
	CreatedAt string `json:"created_at,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	Url string `json:"url,omitempty"`
	Watchlist string `json:"watchlist,omitempty"`
}
