/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TimeHorizon the model 'TimeHorizon'
type TimeHorizon string

// List of TimeHorizon
const (
	SHORT_TIME_HORIZON TimeHorizon = "short_time_horizon"
	MED_TIME_HORIZON TimeHorizon = "med_time_horizon"
	LONG_TIME_HORIZON TimeHorizon = "long_time_horizon"
)
