/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WatchListCreateResponse struct for WatchListCreateResponse
type WatchListCreateResponse struct {
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
	User string `json:"user,omitempty"`
}
