/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InstrumentSplit struct for InstrumentSplit
type InstrumentSplit struct {
	Divisor string `json:"divisor,omitempty"`
	ExecutionDate string `json:"execution_date,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	Multiplier string `json:"multiplier,omitempty"`
	Url string `json:"url,omitempty"`
}
