/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MaritalStatus the model 'MaritalStatus'
type MaritalStatus string

// List of MaritalStatus
const (
	SINGLE MaritalStatus = "single"
	MARRIED MaritalStatus = "married"
)
