/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OpenCloseStrategy the model 'OpenCloseStrategy'
type OpenCloseStrategy string

// List of OpenCloseStrategy
const (
	LONG_CALL OpenCloseStrategy = "long_call"
	LONG_PUT OpenCloseStrategy = "long_put"
	LONG_CALL_SPREAD OpenCloseStrategy = "long_call_spread"
	LONG_PUT_SPREAD OpenCloseStrategy = "long_put_spread"
	SHORT_PUT_SPREAD OpenCloseStrategy = "short_put_spread"
	SHORT_CALL_SPREAD OpenCloseStrategy = "short_call_spread"
	SHORT_PUT_LADDER OpenCloseStrategy = "short_put_ladder"
	SHORT_CALL_LADDER OpenCloseStrategy = "short_call_ladder"
)
