/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TotalNetWorth the model 'TotalNetWorth'
type TotalNetWorth string

// List of TotalNetWorth
const (
	_0_24999 TotalNetWorth = "0_24999"
	_25000_49999 TotalNetWorth = "25000_49999"
	_50000_64999 TotalNetWorth = "50000_64999"
	_65000_99999 TotalNetWorth = "65000_99999"
	_100000_149999 TotalNetWorth = "100000_149999"
	_150000_199999 TotalNetWorth = "150000_199999"
	_250000_499999 TotalNetWorth = "250000_499999"
	_500000_999999 TotalNetWorth = "500000_999999"
	_1000000_INF TotalNetWorth = "1000000_inf"
)
