/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InvestmentExperience the model 'InvestmentExperience'
type InvestmentExperience string

// List of InvestmentExperience
const (
	EXTENSIVE_INVESTMENT_EXP InvestmentExperience = "extensive_investment_exp"
	GOOD_INVESTMENT_EXP InvestmentExperience = "good_investment_exp"
	LIMITED_INVESTMENT_EXP InvestmentExperience = "limited_investment_exp"
	NO_INVESTMENT_EXP InvestmentExperience = "no_investment_exp"
)
