/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Side the model 'Side'
type Side string

// List of Side
const (
	BUY Side = "buy"
	SELL Side = "sell"
)
