/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UserId struct for UserId
type UserId struct {
	Id string `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Username string `json:"username,omitempty"`
}
