/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TimeInForce the model 'TimeInForce'
type TimeInForce string

// List of TimeInForce
const (
	GFD TimeInForce = "gfd"
	GTC TimeInForce = "gtc"
	IOC TimeInForce = "ioc"
	OPG TimeInForce = "opg"
)
