/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OptionChain struct for OptionChain
type OptionChain struct {
	CanOpenPosition bool `json:"can_open_position,omitempty"`
	CashComponent map[string]interface{} `json:"cash_component,omitempty"`
	ExpirationDates []string `json:"expiration_dates,omitempty"`
	Id string `json:"id,omitempty"`
	MinTicks MinTicks `json:"min_ticks,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	TradeValueMultiplier string `json:"trade_value_multiplier,omitempty"`
	UnderlyingInstruments []UnderlyingInstrument `json:"underlying_instruments,omitempty"`
}
