/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// BasicInfo struct for BasicInfo
type BasicInfo struct {
	Address string `json:"address,omitempty"`
	Citizenship string `json:"citizenship,omitempty"`
	City string `json:"city,omitempty"`
	CountryOfResidence string `json:"country_of_residence,omitempty"`
	DateOfBirth string `json:"date_of_birth,omitempty"`
	MaritalStatus MaritalStatus `json:"marital_status,omitempty"`
	NumberDependents string `json:"number_dependents,omitempty"`
	PhoneNumber string `json:"phone_number,omitempty"`
	State string `json:"state,omitempty"`
	TaxIdSsn string `json:"tax_id_ssn,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	User string `json:"user,omitempty"`
	Zipcode string `json:"zipcode,omitempty"`
}
