/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FundamentalsData struct for FundamentalsData
type FundamentalsData struct {
	AverageVolume string `json:"average_volume,omitempty"`
	Description string `json:"description,omitempty"`
	DividendYield string `json:"dividend_yield,omitempty"`
	High string `json:"high,omitempty"`
	High52Weeks string `json:"high_52_weeks,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	Low string `json:"low,omitempty"`
	Low52Weeks string `json:"low_52_weeks,omitempty"`
	MarketCap string `json:"market_cap,omitempty"`
	Open string `json:"open,omitempty"`
	PeRatio string `json:"pe_ratio,omitempty"`
	Volume string `json:"volume,omitempty"`
}
