/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ExecutionType the model 'ExecutionType'
type ExecutionType string

// List of ExecutionType
const (
	MARKET ExecutionType = "market"
	LIMIT ExecutionType = "limit"
)
