/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InstrumentState the model 'InstrumentState'
type InstrumentState string

// List of InstrumentState
const (
	ACTIVE InstrumentState = "active"
	INACTIVE InstrumentState = "inactive"
)
