/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Execution struct for Execution
type Execution struct {
	Id string `json:"id,omitempty"`
	Price float64 `json:"price,omitempty"`
	Quantity float64 `json:"quantity,omitempty"`
	SettlementDate string `json:"settlement_date,omitempty"`
	Timestamp time.Time `json:"timestamp,omitempty"`
}
