/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// Position struct for Position
type Position struct {
	Account string `json:"account,omitempty"`
	AverageBuyPrice string `json:"average_buy_price,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	IntradayAverageBuyPrice string `json:"intraday_average_buy_price,omitempty"`
	IntradayQuantity string `json:"intraday_quantity,omitempty"`
	Quantity string `json:"quantity,omitempty"`
	SharesHeldForBuys string `json:"shares_held_for_buys,omitempty"`
	SharesHeldForSells string `json:"shares_held_for_sells,omitempty"`
	SharesHeldForStockGrants string `json:"shares_held_for_stock_grants,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	Url string `json:"url,omitempty"`
}
