/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InvestmentObjective the model 'InvestmentObjective'
type InvestmentObjective string

// List of InvestmentObjective
const (
	CAP_PRESERVE_INVEST_OBJ InvestmentObjective = "cap_preserve_invest_obj"
	INCOME_INVEST_OBJ InvestmentObjective = "income_invest_obj"
	GROWTH_INVEST_OBJ InvestmentObjective = "growth_invest_obj"
	SPECULATION_INVEST_OBJ InvestmentObjective = "speculation_invest_obj"
	OTHER_INVEST_OBJ InvestmentObjective = "other_invest_obj"
)
