/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountType the model 'AccountType'
type AccountType string

// List of AccountType
const (
	CASH AccountType = "cash"
	MARGIN AccountType = "margin"
)
