/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Trigger the model 'Trigger'
type Trigger string

// List of Trigger
const (
	IMMEDIATE Trigger = "immediate"
	STOP Trigger = "stop"
)
