/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// InvestmentProfile struct for InvestmentProfile
type InvestmentProfile struct {
	AnnualIncome string `json:"annual_income,omitempty"`
	InvestmentExperience string `json:"investment_experience,omitempty"`
	InvestmentObjective string `json:"investment_objective,omitempty"`
	LiquidNetWorth string `json:"liquid_net_worth,omitempty"`
	LiquidityNeeds string `json:"liquidity_needs,omitempty"`
	RiskTolerance string `json:"risk_tolerance,omitempty"`
	SourceOfFunds string `json:"source_of_funds,omitempty"`
	SuitabilityVerified bool `json:"suitability_verified,omitempty"`
	TaxBracket string `json:"tax_bracket,omitempty"`
	TimeHorizon string `json:"time_horizon,omitempty"`
	TotalNetWorth string `json:"total_net_worth,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	User string `json:"user,omitempty"`
}
