/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrderTotalNotional struct for OrderTotalNotional
type OrderTotalNotional struct {
	Amount string `json:"amount,omitempty"`
	CurrencyCode string `json:"currency_code,omitempty"`
	CurrencyId string `json:"currency_id,omitempty"`
}
