/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OptionsMarketData struct for OptionsMarketData
type OptionsMarketData struct {
	AdjustedMarkPrice string `json:"adjusted_mark_price,omitempty"`
	AskPrice string `json:"ask_price,omitempty"`
	AskSize string `json:"ask_size,omitempty"`
	BidPrice string `json:"bid_price,omitempty"`
	BidSize string `json:"bid_size,omitempty"`
	BreakEvenPrice string `json:"break_even_price,omitempty"`
	ChanceOfProfitLong string `json:"chance_of_profit_long,omitempty"`
	ChanceOfProfitShort string `json:"chance_of_profit_short,omitempty"`
	Delta string `json:"delta,omitempty"`
	Gamma string `json:"gamma,omitempty"`
	HighPrice string `json:"high_price,omitempty"`
	ImpliedVolatility string `json:"implied_volatility,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	LastTradePrice string `json:"last_trade_price,omitempty"`
	LastTradeSize string `json:"last_trade_size,omitempty"`
	LowPrice string `json:"low_price,omitempty"`
	MarkPrice string `json:"mark_price,omitempty"`
	OpenInterest string `json:"open_interest,omitempty"`
	PreviousCloseDate string `json:"previous_close_date,omitempty"`
	PreviousClosePrice string `json:"previous_close_price,omitempty"`
	Rho string `json:"rho,omitempty"`
	Theta string `json:"theta,omitempty"`
	Vega string `json:"vega,omitempty"`
	Volume string `json:"volume,omitempty"`
}
