/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SourceOfFunds the model 'SourceOfFunds'
type SourceOfFunds string

// List of SourceOfFunds
const (
	SAVINGS_PERSONAL_INCOME SourceOfFunds = "savings_personal_income"
	PENSION_RETIREMENT SourceOfFunds = "pension_retirement"
	INSURANCE_PAYOUT SourceOfFunds = "insurance_payout"
	INHERITANCE SourceOfFunds = "inheritance"
	GIFT SourceOfFunds = "gift"
	SALE_BUSINESS_OR_PROPERTY SourceOfFunds = "sale_business_or_property"
	OTHER SourceOfFunds = "other"
)
