/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TaxBracket the model 'TaxBracket'
type TaxBracket string

// List of TaxBracket
const (
	_0_PCT TaxBracket = "0_pct"
	_20_PCT TaxBracket = "20_pct"
	_25_PCT TaxBracket = "25_pct"
	_28_PCT TaxBracket = "28_pct"
	_33_PCT TaxBracket = "33_pct"
	_35_PCT TaxBracket = "35_pct"
	_39_6_PCT TaxBracket = "39_6_pct"
)
