/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InstrumentState the model 'InstrumentState'
type InstrumentState string

// List of InstrumentState
const (
	ACTIVE InstrumentState = "active"
	INACTIVE InstrumentState = "inactive"
)
