/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WatchListsData struct for WatchListsData
type WatchListsData struct {
	CreatedAt string `json:"created_at,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	Url string `json:"url,omitempty"`
	Watchlist string `json:"watchlist,omitempty"`
}
