/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CryptoOrderOutput struct for CryptoOrderOutput
type CryptoOrderOutput struct {
	Account string `json:"account,omitempty"`
	AveragePrice string `json:"average_price,omitempty"`
	Cancel string `json:"cancel,omitempty"`
	CancelUrl string `json:"cancel_url,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	CumulativeQuantity string `json:"cumulative_quantity,omitempty"`
	CurrencyPairId string `json:"currency_pair_id,omitempty"`
	Executions []Execution `json:"executions,omitempty"`
	Id string `json:"id,omitempty"`
	LastTransactionAt string `json:"last_transaction_at,omitempty"`
	Price string `json:"price,omitempty"`
	Quantity string `json:"quantity,omitempty"`
	RejectReason string `json:"reject_reason,omitempty"`
	Side Side `json:"side,omitempty"`
	State string `json:"state,omitempty"`
	StopPrice string `json:"stop_price,omitempty"`
	TimeInForce TimeInForce `json:"time_in_force,omitempty"`
	Type string `json:"type,omitempty"`
}
