/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrderState the model 'OrderState'
type OrderState string

// List of OrderState
const (
	QUEUED OrderState = "queued"
	UNCONFIRMED OrderState = "unconfirmed"
	CONFIRMED OrderState = "confirmed"
	PARTIALLY_FILLED OrderState = "partially_filled"
	FILLED OrderState = "filled"
	REJECTED OrderState = "rejected"
	CANCELED OrderState = "canceled"
	FAILED OrderState = "failed"
)
