/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// QuoteData struct for QuoteData
type QuoteData struct {
	AdjustedPreviousClose float64 `json:"adjusted_previous_close,omitempty"`
	AskPrice float64 `json:"ask_price,omitempty"`
	AskSize int32 `json:"ask_size,omitempty"`
	BidPrice float64 `json:"bid_price,omitempty"`
	BidSize int32 `json:"bid_size,omitempty"`
	LastExtendedHoursTradePrice float64 `json:"last_extended_hours_trade_price,omitempty"`
	LastTradePrice float64 `json:"last_trade_price,omitempty"`
	PreviousClose float64 `json:"previous_close,omitempty"`
	PreviousCloseDate string `json:"previous_close_date,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	TradingHalted bool `json:"trading_halted,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
