/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UnderlyingInstrument struct for UnderlyingInstrument
type UnderlyingInstrument struct {
	Id string `json:"id,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	Quantity float32 `json:"quantity,omitempty"`
}
