/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PositionEffect the model 'PositionEffect'
type PositionEffect string

// List of PositionEffect
const (
	OPEN PositionEffect = "open"
	CLOSE PositionEffect = "close"
)
