/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// CashBalances struct for CashBalances
type CashBalances struct {
	BuyingPower string `json:"buying_power,omitempty"`
	Cash string `json:"cash,omitempty"`
	CashAvailableForWithdrawal string `json:"cash_available_for_withdrawal,omitempty"`
	CashHeldForOrders string `json:"cash_held_for_orders,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	UnclearedDeposits string `json:"uncleared_deposits,omitempty"`
	UnsettledFunds string `json:"unsettled_funds,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
