/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CryptoPortfolio struct for CryptoPortfolio
type CryptoPortfolio struct {
	AccountId string `json:"account_id,omitempty"`
	Equity string `json:"equity,omitempty"`
	ExtendedHoursEquity string `json:"extended_hours_equity,omitempty"`
	ExtendedHoursMarketValue string `json:"extended_hours_market_value,omitempty"`
	Id string `json:"id,omitempty"`
}
