/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AuthResponse struct for AuthResponse
type AuthResponse struct {
	MfaRequired string `json:"mfa_required,omitempty"`
	MfaType string `json:"mfa_type,omitempty"`
	Token string `json:"token,omitempty"`
}
