/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MarketData struct for MarketData
type MarketData struct {
	Acronym string `json:"acronym,omitempty"`
	City string `json:"city,omitempty"`
	Country string `json:"country,omitempty"`
	Mic string `json:"mic,omitempty"`
	Name string `json:"name,omitempty"`
	OperatingMic string `json:"operating_mic,omitempty"`
	Timezone string `json:"timezone,omitempty"`
	TodaysHours string `json:"todays_hours,omitempty"`
	Url string `json:"url,omitempty"`
	Website string `json:"website,omitempty"`
}
