/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Portfolio struct for Portfolio
type Portfolio struct {
	Account string `json:"account,omitempty"`
	AdjustedEquityPreviousClose string `json:"adjusted_equity_previous_close,omitempty"`
	Equity string `json:"equity,omitempty"`
	EquityPreviousClose string `json:"equity_previous_close,omitempty"`
	ExcessMaintenance string `json:"excess_maintenance,omitempty"`
	ExcessMaintenanceWithUnclearedDeposits string `json:"excess_maintenance_with_uncleared_deposits,omitempty"`
	ExcessMargin string `json:"excess_margin,omitempty"`
	ExcessMarginWithUnclearedDeposits string `json:"excess_margin_with_uncleared_deposits,omitempty"`
	ExtendedHoursEquity string `json:"extended_hours_equity,omitempty"`
	ExtendedHoursMarketValue string `json:"extended_hours_market_value,omitempty"`
	LastCoreEquity string `json:"last_core_equity,omitempty"`
	LastCoreMarketValue string `json:"last_core_market_value,omitempty"`
	MarketValue string `json:"market_value,omitempty"`
	StartDate string `json:"start_date,omitempty"`
	UnwithdrawableDeposits string `json:"unwithdrawable_deposits,omitempty"`
	UnwithdrawableGrants string `json:"unwithdrawable_grants,omitempty"`
	Url string `json:"url,omitempty"`
	WithdrawableAmount string `json:"withdrawable_amount,omitempty"`
}
