/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Quote struct for Quote
type Quote struct {
	AdjustedPreviousClose string `json:"adjusted_previous_close,omitempty"`
	AskPrice string `json:"ask_price,omitempty"`
	AskSize int32 `json:"ask_size,omitempty"`
	BidPrice string `json:"bid_price,omitempty"`
	BidSize int32 `json:"bid_size,omitempty"`
	LastExtendedHoursTradePrice string `json:"last_extended_hours_trade_price,omitempty"`
	LastTradePrice string `json:"last_trade_price,omitempty"`
	PreviousClose string `json:"previous_close,omitempty"`
	PreviousCloseDate string `json:"previous_close_date,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	TradingHalted bool `json:"trading_halted,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
