/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// LiquidityNeeds the model 'LiquidityNeeds'
type LiquidityNeeds string

// List of LiquidityNeeds
const (
	NOT_IMPORTANT_LIQ_NEED LiquidityNeeds = "not_important_liq_need"
	SOMEWHAT_IMPORTANT_LIQ_NEED LiquidityNeeds = "somewhat_important_liq_need"
	VERY_IMPORTANT_LIQ_NEED LiquidityNeeds = "very_important_liq_need"
)
