/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InstrumentData struct for InstrumentData
type InstrumentData struct {
	BloombergUnique string `json:"bloomberg_unique,omitempty"`
	Country string `json:"country,omitempty"`
	DayTradeRatio float64 `json:"day_trade_ratio,omitempty"`
	Fundamentals string `json:"fundamentals,omitempty"`
	Id string `json:"id,omitempty"`
	ListDate string `json:"list_date,omitempty"`
	MaintenanceRatio float64 `json:"maintenance_ratio,omitempty"`
	MarginInitialRatio float64 `json:"margin_initial_ratio,omitempty"`
	Market string `json:"market,omitempty"`
	MinTickSize float64 `json:"min_tick_size,omitempty"`
	Name string `json:"name,omitempty"`
	Quote string `json:"quote,omitempty"`
	SimpleName string `json:"simple_name,omitempty"`
	Splits string `json:"splits,omitempty"`
	State string `json:"state,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Tradability string `json:"tradability,omitempty"`
	Tradeable string `json:"tradeable,omitempty"`
	Type string `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
}
