/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OptionOrder struct for OptionOrder
type OptionOrder struct {
	CancelUrl string `json:"cancel_url,omitempty"`
	CanceledQuantity string `json:"canceled_quantity,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Direction string `json:"direction,omitempty"`
	Id string `json:"id,omitempty"`
	Legs []OptionOrderLegs `json:"legs,omitempty"`
	PendingQuantity string `json:"pending_quantity,omitempty"`
	Premium string `json:"premium,omitempty"`
	ProcessedPremium string `json:"processed_premium,omitempty"`
	Price string `json:"price,omitempty"`
	ProcessedQuantity string `json:"processed_quantity,omitempty"`
	Quantity string `json:"quantity,omitempty"`
	RefId string `json:"ref_id,omitempty"`
	State string `json:"state,omitempty"`
	TimeInForce string `json:"time_in_force,omitempty"`
	Trigger string `json:"trigger,omitempty"`
	Type string `json:"type,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	ChainId string `json:"chain_id,omitempty"`
	ChainSymbol string `json:"chain_symbol,omitempty"`
	ResponseCategory string `json:"response_category,omitempty"`
	OpeningStrategy string `json:"opening_strategy,omitempty"`
	ClosingStrategy string `json:"closing_strategy,omitempty"`
	StopPrice string `json:"stop_price,omitempty"`
}
