/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WatchListCreateResponse struct for WatchListCreateResponse
type WatchListCreateResponse struct {
	Name string `json:"name,omitempty"`
	Url string `json:"url,omitempty"`
	User string `json:"user,omitempty"`
}
