/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// FundamentalsData struct for FundamentalsData
type FundamentalsData struct {
	AverageVolume float64 `json:"average_volume,omitempty"`
	Description string `json:"description,omitempty"`
	DividendYield float64 `json:"dividend_yield,omitempty"`
	High float64 `json:"high,omitempty"`
	High52Weeks float64 `json:"high_52_weeks,omitempty"`
	Instrument string `json:"instrument,omitempty"`
	Low float64 `json:"low,omitempty"`
	Low52Weeks float64 `json:"low_52_weeks,omitempty"`
	MarketCap float64 `json:"market_cap,omitempty"`
	Open float64 `json:"open,omitempty"`
	PeRatio float64 `json:"pe_ratio,omitempty"`
	Volume float64 `json:"volume,omitempty"`
}
