/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// MarketHours struct for MarketHours
type MarketHours struct {
	ClosesAt time.Time `json:"closes_at,omitempty"`
	Date time.Time `json:"date,omitempty"`
	ExtendedClosesAt time.Time `json:"extended_closes_at,omitempty"`
	ExtendedOpensAt time.Time `json:"extended_opens_at,omitempty"`
	IsOpen bool `json:"is_open,omitempty"`
	NextOpenHours string `json:"next_open_hours,omitempty"`
	OpensAt time.Time `json:"opens_at,omitempty"`
	PreviousOpenHours string `json:"previous_open_hours,omitempty"`
}
