/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CryptoCurrencyPair struct for CryptoCurrencyPair
type CryptoCurrencyPair struct {
	AssetCurrency CryptoAssetCurrency `json:"asset_currency,omitempty"`
	Id string `json:"id,omitempty"`
	MaxOrderSize string `json:"max_order_size,omitempty"`
	MinOrderPriceIncrement string `json:"min_order_price_increment,omitempty"`
	MinOrderSize string `json:"min_order_size,omitempty"`
	Name string `json:"name,omitempty"`
	QuoteCurrency QuoteCurrency `json:"quote_currency,omitempty"`
	Symbol string `json:"symbol,omitempty"`
	Tradability string `json:"tradability,omitempty"`
}
