/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrderResponse struct for OrderResponse
type OrderResponse struct {
	Schema Order `json:"schema,omitempty"`
}
