/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// RiskTolerance the model 'RiskTolerance'
type RiskTolerance string

// List of RiskTolerance
const (
	LOW_RISK_TOLERANCE RiskTolerance = "low_risk_tolerance"
	MED_RISK_TOLERANCE RiskTolerance = "med_risk_tolerance"
	HIGH_RISK_TOLERANCE RiskTolerance = "high_risk_tolerance"
)
