/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// GetOptionOrdersResponse struct for GetOptionOrdersResponse
type GetOptionOrdersResponse struct {
	Next string `json:"next,omitempty"`
	Previous string `json:"previous,omitempty"`
	Results []OptionOrder `json:"results,omitempty"`
}
