/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UserInfo struct for UserInfo
type UserInfo struct {
	AdditionalInfo string `json:"additional_info,omitempty"`
	BasicInfo string `json:"basic_info,omitempty"`
	Email string `json:"email,omitempty"`
	Employment string `json:"employment,omitempty"`
	FirstName string `json:"first_name,omitempty"`
	Id string `json:"id,omitempty"`
	IdInfo string `json:"id_info,omitempty"`
	InternationalInfo string `json:"international_info,omitempty"`
	InvestmentProfile string `json:"investment_profile,omitempty"`
	LastName string `json:"last_name,omitempty"`
	Url string `json:"url,omitempty"`
	Username string `json:"username,omitempty"`
}
