/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// QuoteCurrency struct for QuoteCurrency
type QuoteCurrency struct {
	Code string `json:"code,omitempty"`
	Id string `json:"id,omitempty"`
	Increment string `json:"increment,omitempty"`
	Name string `json:"name,omitempty"`
	Type string `json:"type,omitempty"`
}
