/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountType the model 'AccountType'
type AccountType string

// List of AccountType
const (
	CASH AccountType = "cash"
	MARGIN AccountType = "margin"
)
