/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// MarginBalances struct for MarginBalances
type MarginBalances struct {
	Cash string `json:"cash,omitempty"`
	CashAvailableForWithdrawal string `json:"cash_available_for_withdrawal,omitempty"`
	CashHeldForOrders string `json:"cash_held_for_orders,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	DayTradeBuyingPower string `json:"day_trade_buying_power,omitempty"`
	DayTradeBuyingPowerHeldForOrders string `json:"day_trade_buying_power_held_for_orders,omitempty"`
	DayTradeRatio string `json:"day_trade_ratio,omitempty"`
	MarginLimit string `json:"margin_limit,omitempty"`
	MarkedPatternDayTraderDate time.Time `json:"marked_pattern_day_trader_date,omitempty"`
	OvernightBuyingPower string `json:"overnight_buying_power,omitempty"`
	OvernightBuyingPowerHeldForOrders string `json:"overnight_buying_power_held_for_orders,omitempty"`
	OvernightRatio string `json:"overnight_ratio,omitempty"`
	UnallocatedMarginCash string `json:"unallocated_margin_cash,omitempty"`
	UnclearedDeposits string `json:"uncleared_deposits,omitempty"`
	UnsettledFunds string `json:"unsettled_funds,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
