/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OptionOrderExecutions struct for OptionOrderExecutions
type OptionOrderExecutions struct {
	Id string `json:"id,omitempty"`
	Price string `json:"price,omitempty"`
	Quantity string `json:"quantity,omitempty"`
	SettlementDate string `json:"settlement_date,omitempty"`
	Timestamp string `json:"timestamp,omitempty"`
}
