/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Trigger the model 'Trigger'
type Trigger string

// List of Trigger
const (
	IMMEDIATE Trigger = "immediate"
	STOP Trigger = "stop"
)
