/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OrderAction the model 'OrderAction'
type OrderAction string

// List of OrderAction
const (
	ORDER OrderAction = "order"
	STATUS OrderAction = "status"
	CANCEL OrderAction = "cancel"
	HISTORY OrderAction = "history"
)
