/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OptionOrderInput struct for OptionOrderInput
type OptionOrderInput struct {
	Account string `json:"account,omitempty"`
	Direction Direction `json:"direction,omitempty"`
	Legs []Leg `json:"legs,omitempty"`
	OverrideDayTradeChecks bool `json:"override_day_trade_checks,omitempty"`
	OverrideDtbpChecks bool `json:"override_dtbp_checks,omitempty"`
	Price string `json:"price,omitempty"`
	Quantity string `json:"quantity,omitempty"`
	RefId string `json:"ref_id,omitempty"`
	TimeInForce TimeInForce `json:"time_in_force,omitempty"`
	Trigger Trigger `json:"trigger,omitempty"`
	Type ExecutionType `json:"type,omitempty"`
}
