/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// UserId struct for UserId
type UserId struct {
	Id string `json:"id,omitempty"`
	Url string `json:"url,omitempty"`
	Username string `json:"username,omitempty"`
}
