/*
 * Api Documentation
 *
 * Api Documentation
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TimeHorizon the model 'TimeHorizon'
type TimeHorizon string

// List of TimeHorizon
const (
	SHORT_TIME_HORIZON TimeHorizon = "short_time_horizon"
	MED_TIME_HORIZON TimeHorizon = "med_time_horizon"
	LONG_TIME_HORIZON TimeHorizon = "long_time_horizon"
)
