/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// TimeInForce the model 'TimeInForce'
type TimeInForce string

// List of TimeInForce
const (
	GFD TimeInForce = "gfd"
	GTC TimeInForce = "gtc"
	IOC TimeInForce = "ioc"
	OPG TimeInForce = "opg"
)
