/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Auth struct for Auth
type Auth struct {
	MfaRequired string `json:"mfa_required,omitempty"`
	MfaType string `json:"mfa_type,omitempty"`
	Token string `json:"token,omitempty"`
}
