/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
import (
	"time"
)
// MarginBalances struct for MarginBalances
type MarginBalances struct {
	Cash float64 `json:"cash,omitempty"`
	CashAvailableForWithdrawal float64 `json:"cash_available_for_withdrawal,omitempty"`
	CashHeldForOrders float64 `json:"cash_held_for_orders,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	DayTradeBuyingPower float64 `json:"day_trade_buying_power,omitempty"`
	DayTradeBuyingPowerHeldForOrders float64 `json:"day_trade_buying_power_held_for_orders,omitempty"`
	DayTradeRatio float64 `json:"day_trade_ratio,omitempty"`
	MarginLimit float64 `json:"margin_limit,omitempty"`
	MarkedPatternDayTraderDate time.Time `json:"marked_pattern_day_trader_date,omitempty"`
	OvernightBuyingPower float64 `json:"overnight_buying_power,omitempty"`
	OvernightBuyingPowerHeldForOrders float64 `json:"overnight_buying_power_held_for_orders,omitempty"`
	OvernightRatio float64 `json:"overnight_ratio,omitempty"`
	UnallocatedMarginCash float64 `json:"unallocated_margin_cash,omitempty"`
	UnclearedDeposits float64 `json:"uncleared_deposits,omitempty"`
	UnsettledFunds float64 `json:"unsettled_funds,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
