/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CryptoAssetCurrency struct for CryptoAssetCurrency
type CryptoAssetCurrency struct {
	BrandColor string `json:"brand_color,omitempty"`
	Code string `json:"code,omitempty"`
	Id string `json:"id,omitempty"`
	Increment string `json:"increment,omitempty"`
	Name *interface{} `json:"name,omitempty"`
}
