/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// CryptoAccount struct for CryptoAccount
type CryptoAccount struct {
	Id string `json:"id,omitempty"`
	Status string `json:"status,omitempty"`
	UserId string `json:"user_id,omitempty"`
}
