/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Account struct for Account
type Account struct {
	Option string `json:"option,omitempty"`
	PositionEffect string `json:"position_effect,omitempty"`
	RatioQuantity string `json:"ratio_quantity,omitempty"`
	Side string `json:"side,omitempty"`
}
