/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MaritalStatus the model 'MaritalStatus'
type MaritalStatus string

// List of MaritalStatus
const (
	SINGLE MaritalStatus = "single"
	MARRIED MaritalStatus = "married"
)
