/*
 * Robinhood API
 *
 * Robinhood API Documentation
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// OptionOrderLeg struct for OptionOrderLeg
type OptionOrderLeg struct {
	Executions []OptionOrderLegExecutions `json:"executions,omitempty"`
	Id string `json:"id,omitempty"`
	Option string `json:"option,omitempty"`
	PositionEffect PositionEffect `json:"position_effect,omitempty"`
	RatioQuantity float32 `json:"ratio_quantity,omitempty"`
	Side Side `json:"side,omitempty"`
}
